---
  - name: enroll
    hosts: localhost
    tasks:
      - name: enroll | apt: update cache
        ansible.builtin.apt:
          update_cache: yes

      - name: enroll | install cron
        ansible.builtin.apt:
          name: cron
          start: present

      - name: ensure cron is running
        ansible.builtin.service:
          name: cron
          state: started

      - name: run ansible-pull as cron job
        cron:
          name: ansible-pull
          job: ansible-pull --url https://github.com/polarlabs/autopilot play-baseline.yml
          user: root
          minute: "*/5"
          state: present

