---
- name: enroll
  hosts: localhost
  tasks:
  - name: enroll | apt update cache
    ansible.builtin.apt:
      update_cache: yes
    changed_when: false

  - name: enroll | apt install cron
    ansible.builtin.apt:
      name: cron
      state: present

  - name: enroll | service start cron
    ansible.builtin.service:
      name: cron
      state: started

  - name: enroll | cron schedule ansible-pull
    cron:
      name: ansible-pull
      job: ansible-pull --url https://github.com/polarlabs/autopilot play-baseline.yml
      user: root
      minute: "*/5"
      state: present

