---
- name: Enroll
  hosts: localhost
  connection: local

  tasks:
    - name: Enroll | apt update cache
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

    - name: Enroll | apt install cron
      ansible.builtin.apt:
        name: cron
        state: present

    - name: Enroll | service start cron
      ansible.builtin.service:
        name: cron
        state: started

    - name: Enroll | cron schedule ansible-pull
      ansible.builtin.cron:
        name: ansible-pull
        job: ansible-pull --url https://github.com/polarlabs/autopilot --clean --sleep 15 --force play-config.yml
        user: root
        minute: "*/5"
        state: present
