---

- name: Build host | apt install prereqs
  ansible.builtin.apt:
    pkg:
      - gcc
      - libssl-dev
      - pkgconf
    state: present

- name: Build host | Create build group
  ansible.builtin.group:
    name: "build"
    gid: 1001
    state: "present"

- name: Build host | Create build user
  ansible.builtin.user:
    name: "build"
    uid: 1001
    group: "build"
    groups: "docker"
    append: true
    comment: "Build"
    shell: "/bin/bash"
    state: "present"

- name: Build host | Check if cargo is installed
  ansible.builtin.command:
    cmd: "cargo --version"
  register: cargo_exists
  ignore_errors: true
  changed_when: false
