---

- name: Kodiak web server | Copy docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/srv/web/docker-compose.yml"
    mode: "0400"
  notify:
    - "Kodiak web server | Start container"
