---

- name: Kodiak web server | Copy docker-compose.yml
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/srv/web/docker-compose.yml"
    mode: "0400"

- name: Kodiak web server | Docker compose
  community.docker.docker_compose:
    project_src: "/srv/web"
    state: present
